package com.attendo.core.data

import com.attendo.core.engine.AttendanceEngine
import com.attendo.core.engine.RoomAvailability
import com.attendo.core.engine.SessionGenerator
import com.attendo.core.model.AcademicCalendar
import com.attendo.core.model.Course
import com.attendo.core.model.SessionKind
import com.attendo.core.model.SessionPattern
import com.attendo.core.model.SessionStatus
import com.attendo.core.model.UnitMask
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.Test
import java.io.File
import java.time.DayOfWeek
import java.time.LocalDate

/**
 * The three ways a course can meet the 17 September 2026 timetable, over the file that ships.
 *
 * [SessionEffectStartTest] pins what `effectiveFrom` does to generation. This pins what the app
 * *hands* it, which is where the defect actually was, and it does so through the real seam: the
 * bundled CSV, read by the real parser, seeded by the real seeder, generated by the real
 * generator. Nothing here builds a fixture that the app could not build.
 *
 * The brief names three cases and warns that they must not be conflated:
 *
 * | | the course | its first pattern |
 * |---|---|---|
 * | **A** | ran from the term start, slots untouched | 28 July 2026 |
 * | **B** | ran from the term start, slots revised | old slot ends 16 September, replacement starts 17 September |
 * | **C** | introduced by the September edition | 17 September 2026, and nothing before it |
 *
 * A single date rule for everything collapses A into C — which is the mistake this file exists
 * to catch, and why every expected date below is written out rather than read from the helper
 * being tested. The one test that does ask the helper ([every introduced code is taught…]) is
 * asking it a different question: whether the set still describes the bundled file.
 */
class IntroducedCourseDatingTest {

    private fun asset(name: String): String {
        val file = File("../app/src/main/assets/$name")
        assertTrue("missing bundled asset ${file.absolutePath}", file.isFile)
        return file.readText()
    }

    /** The July edition's term start. Written out, not read from the rule under test. */
    private val termStart = LocalDate.of(2026, 7, 28)

    /** The day the faculty reissued the grid. Written out for the same reason. */
    private val edition = LocalDate.of(2026, 9, 17)

    private val calendar = AcademicCalendar(termStart, LocalDate.of(2026, 11, 20))

    private val imported = TimetableCsv.parse(asset("timetable.csv"))
    private val subjects = Glossary.parse(asset("subjects.csv"))

    /** The rule the app hands the seeder, spelled exactly as `SeedViewModel` spells it. */
    private fun seed(section: String, batch: String? = null) = SectionSeeder.plan(
        bookings = imported.bookings,
        section = section,
        termStart = termStart,
        batch = batch,
        subjects = subjects,
        startFor = { code -> TimetableMigration.effectiveFromFor(code, termStart) },
    )

    private fun proposal(plan: SeedPlan, code: String): SeedProposal =
        plan.proposals.firstOrNull { it.course.code == code }
            ?: throw AssertionError("$code is not offered; got ${plan.proposals.map { it.course.code }}")

    /** Every date [proposal]'s slots produce, as the dashboard would. */
    private fun generated(proposal: SeedProposal): List<LocalDate> =
        SessionGenerator.draftsFor(proposal.patterns, emptyList(), termStart, calendar.termEnd, calendar)
            .map { it.date }

    // ---- C. a subject the September edition introduces -----------------------

    @Test
    fun `a subject the September grid introduces is dated from the September grid`() {
        // `FMB` is on all six 1st-year pages and on none of July's. The seeder is the only way
        // it reaches a course list, so this is the line that decides whether a student who ticks
        // it inherits six weeks of a paper that did not exist.
        val fmb = proposal(seed("1st Yr CSE-A"), "FMB")

        assertEquals(setOf(LocalDate.of(2026, 9, 17)), fmb.patterns.map { it.effectiveFrom }.toSet())
    }

    @Test
    fun `and none of its classes are proposed before the 17th`() {
        val fmb = proposal(seed("1st Yr CSE-A"), "FMB")

        val dates = generated(fmb)

        assertTrue("the fixture must produce something, or this proves nothing", dates.isNotEmpty())
        assertEquals(
            "every class of a paper that was not taught belongs on or after the day it began",
            emptyList<LocalDate>(),
            dates.filter { it.isBefore(LocalDate.of(2026, 9, 17)) },
        )
        assertTrue(dates.any { it.isAfter(LocalDate.of(2026, 9, 17)) })
    }

    @Test
    fun `and the six weeks it did not run never reach its denominator`() {
        // Stamped with an id, as `applySeed` stamps it, so the sessions and the course line up.
        val seeded = proposal(seed("1st Yr CSE-A"), "FMB").withCourseId(1L)

        // Answered and missed, which is the worst case: an unreviewed row is invisible, but a
        // row with an answer in it is counted. If the July weeks were generated they are now
        // failures on a course that had not started.
        val drafts = SessionGenerator.draftsFor(seeded.patterns, emptyList(), termStart, calendar.termEnd, calendar)
        val sessions = drafts.map {
            it.toSession().copy(status = SessionStatus.HELD, unitsMask = UnitMask.NONE)
        }

        val stats = AttendanceEngine.courseStats(seeded.course, sessions, today = calendar.termEnd)

        assertEquals("nothing was attended", 0, stats.tally.unitsAttended)
        assertEquals(
            "the denominator is exactly the hours the grid teaches from the 17th on",
            drafts.filterNot { it.date.isBefore(LocalDate.of(2026, 9, 17)) }.sumOf { it.unitsPlanned },
            stats.tally.unitsHeld,
        )

        // The counterfactual, on the file that ships: the only difference below is the date the
        // pattern was given. This is the figure a student is judged on, so it is the one that
        // says what the defect cost.
        val asItWas = seeded.patterns.map { it.copy(effectiveFrom = termStart) }
        val inflated = SessionGenerator.draftsFor(asItWas, emptyList(), termStart, calendar.termEnd, calendar)
            .map { it.toSession().copy(status = SessionStatus.HELD, unitsMask = UnitMask.NONE) }

        assertTrue(
            "dating it from July would have invented weeks the student is judged on",
            AttendanceEngine.courseStats(seeded.course, inflated, today = calendar.termEnd).tally.unitsHeld >
                stats.tally.unitsHeld,
        )
    }

    // ---- A. a course that was already running --------------------------------

    @Test
    fun `a course the July grid taught keeps the July start`() {
        // `M-1` is on the same page as `FMB` and was taught from July, so it must not be dated
        // with it. This is case A against case C on one page, which is where a global rule shows.
        val m1 = proposal(seed("1st Yr CSE-A"), "M-1")

        assertEquals(setOf(LocalDate.of(2026, 7, 28)), m1.patterns.map { it.effectiveFrom }.toSet())
        assertTrue(
            "and it does generate the weeks before the edition",
            generated(m1).any { it.isBefore(LocalDate.of(2026, 9, 17)) },
        )
    }

    @Test
    fun `re-ticking an existing course does not move its start`() {
        // The seed screen is how a course is added *and* re-added, and it cannot tell the two
        // apart — whatever is ticked is proposed afresh. So every course the July grid taught has
        // to come back dated from July, on every one of the twenty-two pages, or a student who
        // re-seeds in September silently loses their term's figures.
        val bornOn: Map<LocalDate, List<String>> = RoomAvailability.sections(imported.bookings)
            .flatMap { section -> seed(section).proposals }
            .groupBy { it.patterns.first().effectiveFrom }
            .mapValues { (_, proposals) -> proposals.map { it.course.code }.distinct().sorted() }

        assertEquals(
            "two dates, and no third: the term the July grid began and the edition that replaced it",
            listOf(LocalDate.of(2026, 7, 28), LocalDate.of(2026, 9, 17)),
            bornOn.keys.sorted(),
        )
        // Every code dated from September is one the edition introduces, and vice versa — so the
        // set is not merely *a* set of codes, it is the right one.
        assertEquals(
            TimetableMigration.INTRODUCED.sorted(),
            bornOn.getValue(LocalDate.of(2026, 9, 17)).filterNot { it.endsWith(" Lab") || it.endsWith(" Tutorial") },
        )
        assertTrue(
            "and the July side is everything else: ${bornOn.getValue(LocalDate.of(2026, 7, 28)).size} codes",
            bornOn.getValue(LocalDate.of(2026, 7, 28)).size > 40,
        )
    }

    // ---- B. a course that was running, with slots the edition revised ---------

    @Test
    fun `a revised slot of a running course closes the day before its replacement opens`() {
        val course = Course(id = 1L, name = "Mathematics I", code = "M-1")
        val asItWas = SessionPattern(
            id = 11L,
            courseId = course.id,
            dayOfWeek = DayOfWeek.MONDAY,
            startHour = 9,
            units = 1,
            kind = SessionKind.LECTURE,
            room = "204",
            effectiveFrom = termStart,
        )
        val movedTo = proposal(seed("1st Yr CSE-A"), "M-1")
            .let { SeedProposal(it.course, it.patterns.take(1)) }
            .withCourseId(course.id)

        val change = TimetableMigration.plan(listOf(course), listOf(asItWas), listOf(movedTo))
            .changes
            .single()

        assertEquals(
            "the slot that ran keeps the day it opened",
            LocalDate.of(2026, 7, 28),
            change.retired.single().effectiveFrom,
        )
        assertEquals(
            "and the slot that replaced it opens on the edition, not on the term start",
            LocalDate.of(2026, 9, 17),
            change.added.single().effectiveFrom,
        )

        // The same two facts as the generator sees them, which is what the student ends up with.
        val dates = SessionGenerator.draftsFor(
            patterns = listOf(asItWas.retiredAfter(LocalDate.of(2026, 9, 16)), change.added.single()),
            existing = emptyList(),
            from = termStart,
            to = calendar.termEnd,
            calendar = calendar,
        ).groupBy { it.patternId }

        val old = dates.getValue(11L).map { it.date }
        val replacement = dates.getValue(change.added.single().id).map { it.date }

        assertTrue(old.isNotEmpty() && replacement.isNotEmpty())
        assertTrue("July to the 16th belongs to the slot that ran", old.all { it.isBefore(LocalDate.of(2026, 9, 17)) })
        assertTrue("and the 17th onwards to the one that replaced it", replacement.all { !it.isBefore(LocalDate.of(2026, 9, 17)) })
    }

    // ---- the renamed subject, which is none of the three ---------------------

    @Test
    fun `the renamed subject keeps the term start, because it was taught all along`() {
        // `FIT INDIA` is a code the September grid prints and July's does not — which is exactly
        // the shape of case C, and exactly why the shape is not the test. The sports hour ran
        // from July under `SFL`, so a student re-seeding it in September is re-adding a course
        // with a term behind it, and dating it from the 17th would delete that term.
        assertFalse("a rename is not an introduction", TimetableMigration.introduces("FIT INDIA"))
        assertEquals("FIT INDIA", TimetableMigration.renamed("SFL"))

        val fitIndia = proposal(seed("2nd Yr CSE-A"), "FIT INDIA")

        assertEquals(setOf(LocalDate.of(2026, 7, 28)), fitIndia.patterns.map { it.effectiveFrom }.toSet())
    }

    @Test
    fun `and the two codes that look alike are not`() {
        // `DE` was not on the July grid; `DE-1` was, in the 2nd year, under a code that merely
        // starts with the same two letters. A prefix rule written without the space would merge
        // them and date a course with a term of history from September.
        assertTrue(TimetableMigration.introduces("DE"))
        assertFalse(TimetableMigration.introduces("DE-1"))
        assertEquals(
            LocalDate.of(2026, 9, 17),
            proposal(seed("1st Yr CSE-A"), "DE").patterns.first().effectiveFrom,
        )
        assertEquals(
            LocalDate.of(2026, 7, 28),
            proposal(seed("2nd Yr ECE-A"), "DE-1").patterns.first().effectiveFrom,
        )
    }

    @Test
    fun `every introduced code is taught by the bundled file, and none of them is an old one`() {
        // The set is a claim about this edition, so it is checked against this edition rather
        // than trusted. A code left behind by a later import would silently start dating a course
        // that has been running since July from September.
        val taught = imported.bookings.map { SectionSeeder.baseCode(it.subject, subjects) }.toSet()

        assertEquals(
            "every code is on a page",
            emptyList<String>(),
            TimetableMigration.INTRODUCED.filterNot { it in taught },
        )
        assertTrue(
            "and a subject July taught is not in it",
            listOf("SFL", "DE-1", "ECA", "DBMS", "M-1", "VLSI").none(TimetableMigration::introduces),
        )
    }
}
